image: maven:3.6-jdk-8-alpine

pipelines:
  default:
    - step:
        name: Create Java JOpt Rest Example Sandbox
        services:
          - docker
        script:
          - cd ./sandbox/java/
          - myVersion=1.2 
          - docker version
          - docker build -t dnaevolutions/jopt_rest_example_server:${myVersion} .
          - docker tag dnaevolutions/jopt_rest_example_server:${myVersion} dnaevolutions/jopt_rest_example_server:latest
          - docker login --username $DOCKERHUB_USER --password $DOCKERHUB_PASS
          - docker push dnaevolutions/jopt_rest_example_server:latest
          - docker push dnaevolutions/jopt_rest_example_server:${myVersion}
definitions:
  services:
    docker:
      memory: 1024