package com.dna.jopt.rest.client.util.testinputcreation;

/*-
 * #%L
 * JOpt Java REST Client Examples
 * %%
 * Copyright (C) 2017 - 2022 DNA Evolutions GmbH
 * %%
 * This file is subject to the terms and conditions defined in file 'LICENSE.md',
 * which is part of this repository.
 * 
 * If not, see <https://www.dna-evolutions.com/agb-conditions-and-terms/>.
 * #L%
 */

public class TestSnapshotInput {
    
    
    private TestSnapshotInput() {
	// Nothing to do
    }

    public static String DEFAULT_PUBLIC_INPUT_JSON_WITHOUT_LICENSE = "{\r\n"
    	+ "  \"ident\" : \"MyJOptRun\",\r\n"
    	+ "  \"nodes\" : [ {\r\n"
    	+ "    \"id\" : \"Koeln\",\r\n"
    	+ "    \"type\" : {\r\n"
    	+ "      \"position\" : {\r\n"
    	+ "        \"latitude\" : 50.9333,\r\n"
    	+ "        \"longitude\" : 6.95,\r\n"
    	+ "        \"locationId\" : \"Koeln\"\r\n"
    	+ "      },\r\n"
    	+ "      \"typeName\" : \"Geo\"\r\n"
    	+ "    },\r\n"
    	+ "    \"openingHours\" : [ {\r\n"
    	+ "      \"begin\" : \"2025-05-06T06:00:00Z\",\r\n"
    	+ "      \"end\" : \"2025-05-06T15:00:00Z\",\r\n"
    	+ "      \"zoneId\" : \"Europe/Berlin\"\r\n"
    	+ "    }, {\r\n"
    	+ "      \"begin\" : \"2025-05-07T06:00:00Z\",\r\n"
    	+ "      \"end\" : \"2025-05-07T15:00:00Z\",\r\n"
    	+ "      \"zoneId\" : \"Europe/Berlin\"\r\n"
    	+ "    } ],\r\n"
    	+ "    \"visitDuration\" : \"PT20M\",\r\n"
    	+ "    \"priority\" : 1\r\n"
    	+ "  }, {\r\n"
    	+ "    \"id\" : \"Essen\",\r\n"
    	+ "    \"type\" : {\r\n"
    	+ "      \"position\" : {\r\n"
    	+ "        \"latitude\" : 51.45,\r\n"
    	+ "        \"longitude\" : 7.01667,\r\n"
    	+ "        \"locationId\" : \"Essen\"\r\n"
    	+ "      },\r\n"
    	+ "      \"typeName\" : \"Geo\"\r\n"
    	+ "    },\r\n"
    	+ "    \"openingHours\" : [ {\r\n"
    	+ "      \"begin\" : \"2025-05-06T06:00:00Z\",\r\n"
    	+ "      \"end\" : \"2025-05-06T15:00:00Z\",\r\n"
    	+ "      \"zoneId\" : \"Europe/Berlin\"\r\n"
    	+ "    }, {\r\n"
    	+ "      \"begin\" : \"2025-05-07T06:00:00Z\",\r\n"
    	+ "      \"end\" : \"2025-05-07T15:00:00Z\",\r\n"
    	+ "      \"zoneId\" : \"Europe/Berlin\"\r\n"
    	+ "    } ],\r\n"
    	+ "    \"visitDuration\" : \"PT20M\",\r\n"
    	+ "    \"priority\" : 1\r\n"
    	+ "  }, {\r\n"
    	+ "    \"id\" : \"Dueren\",\r\n"
    	+ "    \"type\" : {\r\n"
    	+ "      \"position\" : {\r\n"
    	+ "        \"latitude\" : 50.8,\r\n"
    	+ "        \"longitude\" : 6.48333,\r\n"
    	+ "        \"locationId\" : \"Dueren\"\r\n"
    	+ "      },\r\n"
    	+ "      \"typeName\" : \"Geo\"\r\n"
    	+ "    },\r\n"
    	+ "    \"openingHours\" : [ {\r\n"
    	+ "      \"begin\" : \"2025-05-06T06:00:00Z\",\r\n"
    	+ "      \"end\" : \"2025-05-06T15:00:00Z\",\r\n"
    	+ "      \"zoneId\" : \"Europe/Berlin\"\r\n"
    	+ "    }, {\r\n"
    	+ "      \"begin\" : \"2025-05-07T06:00:00Z\",\r\n"
    	+ "      \"end\" : \"2025-05-07T15:00:00Z\",\r\n"
    	+ "      \"zoneId\" : \"Europe/Berlin\"\r\n"
    	+ "    } ],\r\n"
    	+ "    \"visitDuration\" : \"PT20M\",\r\n"
    	+ "    \"priority\" : 1\r\n"
    	+ "  }, {\r\n"
    	+ "    \"id\" : \"Nuernberg\",\r\n"
    	+ "    \"type\" : {\r\n"
    	+ "      \"position\" : {\r\n"
    	+ "        \"latitude\" : 49.4478,\r\n"
    	+ "        \"longitude\" : 11.0683,\r\n"
    	+ "        \"locationId\" : \"Nuernberg\"\r\n"
    	+ "      },\r\n"
    	+ "      \"typeName\" : \"Geo\"\r\n"
    	+ "    },\r\n"
    	+ "    \"openingHours\" : [ {\r\n"
    	+ "      \"begin\" : \"2025-05-06T06:00:00Z\",\r\n"
    	+ "      \"end\" : \"2025-05-06T15:00:00Z\",\r\n"
    	+ "      \"zoneId\" : \"Europe/Berlin\"\r\n"
    	+ "    }, {\r\n"
    	+ "      \"begin\" : \"2025-05-07T06:00:00Z\",\r\n"
    	+ "      \"end\" : \"2025-05-07T15:00:00Z\",\r\n"
    	+ "      \"zoneId\" : \"Europe/Berlin\"\r\n"
    	+ "    } ],\r\n"
    	+ "    \"visitDuration\" : \"PT20M\",\r\n"
    	+ "    \"priority\" : 1\r\n"
    	+ "  }, {\r\n"
    	+ "    \"id\" : \"Heilbronn\",\r\n"
    	+ "    \"type\" : {\r\n"
    	+ "      \"position\" : {\r\n"
    	+ "        \"latitude\" : 49.1403,\r\n"
    	+ "        \"longitude\" : 9.22,\r\n"
    	+ "        \"locationId\" : \"Heilbronn\"\r\n"
    	+ "      },\r\n"
    	+ "      \"typeName\" : \"Geo\"\r\n"
    	+ "    },\r\n"
    	+ "    \"openingHours\" : [ {\r\n"
    	+ "      \"begin\" : \"2025-05-06T06:00:00Z\",\r\n"
    	+ "      \"end\" : \"2025-05-06T15:00:00Z\",\r\n"
    	+ "      \"zoneId\" : \"Europe/Berlin\"\r\n"
    	+ "    }, {\r\n"
    	+ "      \"begin\" : \"2025-05-07T06:00:00Z\",\r\n"
    	+ "      \"end\" : \"2025-05-07T15:00:00Z\",\r\n"
    	+ "      \"zoneId\" : \"Europe/Berlin\"\r\n"
    	+ "    } ],\r\n"
    	+ "    \"visitDuration\" : \"PT20M\",\r\n"
    	+ "    \"priority\" : 1\r\n"
    	+ "  }, {\r\n"
    	+ "    \"id\" : \"Wuppertal\",\r\n"
    	+ "    \"type\" : {\r\n"
    	+ "      \"position\" : {\r\n"
    	+ "        \"latitude\" : 51.2667,\r\n"
    	+ "        \"longitude\" : 7.18333,\r\n"
    	+ "        \"locationId\" : \"Wuppertal\"\r\n"
    	+ "      },\r\n"
    	+ "      \"typeName\" : \"Geo\"\r\n"
    	+ "    },\r\n"
    	+ "    \"openingHours\" : [ {\r\n"
    	+ "      \"begin\" : \"2025-05-06T06:00:00Z\",\r\n"
    	+ "      \"end\" : \"2025-05-06T15:00:00Z\",\r\n"
    	+ "      \"zoneId\" : \"Europe/Berlin\"\r\n"
    	+ "    }, {\r\n"
    	+ "      \"begin\" : \"2025-05-07T06:00:00Z\",\r\n"
    	+ "      \"end\" : \"2025-05-07T15:00:00Z\",\r\n"
    	+ "      \"zoneId\" : \"Europe/Berlin\"\r\n"
    	+ "    } ],\r\n"
    	+ "    \"visitDuration\" : \"PT20M\",\r\n"
    	+ "    \"priority\" : 1\r\n"
    	+ "  }, {\r\n"
    	+ "    \"id\" : \"Aachen\",\r\n"
    	+ "    \"type\" : {\r\n"
    	+ "      \"position\" : {\r\n"
    	+ "        \"latitude\" : 50.775346,\r\n"
    	+ "        \"longitude\" : 6.083887,\r\n"
    	+ "        \"locationId\" : \"Aachen\"\r\n"
    	+ "      },\r\n"
    	+ "      \"typeName\" : \"Geo\"\r\n"
    	+ "    },\r\n"
    	+ "    \"openingHours\" : [ {\r\n"
    	+ "      \"begin\" : \"2025-05-06T06:00:00Z\",\r\n"
    	+ "      \"end\" : \"2025-05-06T15:00:00Z\",\r\n"
    	+ "      \"zoneId\" : \"Europe/Berlin\"\r\n"
    	+ "    }, {\r\n"
    	+ "      \"begin\" : \"2025-05-07T06:00:00Z\",\r\n"
    	+ "      \"end\" : \"2025-05-07T15:00:00Z\",\r\n"
    	+ "      \"zoneId\" : \"Europe/Berlin\"\r\n"
    	+ "    } ],\r\n"
    	+ "    \"visitDuration\" : \"PT20M\",\r\n"
    	+ "    \"priority\" : 1\r\n"
    	+ "  } ],\r\n"
    	+ "  \"resources\" : [ {\r\n"
    	+ "    \"id\" : \"Jack from Aachen\",\r\n"
    	+ "    \"type\" : {\r\n"
    	+ "      \"typeName\" : \"Capacity\"\r\n"
    	+ "    },\r\n"
    	+ "    \"position\" : {\r\n"
    	+ "      \"latitude\" : 50.775346,\r\n"
    	+ "      \"longitude\" : 6.083887,\r\n"
    	+ "      \"locationId\" : \"Jack from Aachen\"\r\n"
    	+ "    },\r\n"
    	+ "    \"workingHours\" : [ {\r\n"
    	+ "      \"begin\" : \"2025-05-06T06:00:00Z\",\r\n"
    	+ "      \"end\" : \"2025-05-06T15:00:00Z\",\r\n"
    	+ "      \"zoneId\" : \"Europe/Berlin\"\r\n"
    	+ "    }, {\r\n"
    	+ "      \"begin\" : \"2025-05-07T06:00:00Z\",\r\n"
    	+ "      \"end\" : \"2025-05-07T15:00:00Z\",\r\n"
    	+ "      \"zoneId\" : \"Europe/Berlin\"\r\n"
    	+ "    } ],\r\n"
    	+ "    \"maxTime\" : \"PT9H\",\r\n"
    	+ "    \"maxDistance\" : \"1200.0 km\",\r\n"
    	+ "    \"co2emissionFactor\" : 0.377\r\n"
    	+ "  } ],\r\n"
    	+ "  \"optimizationOptions\" : {\r\n"
    	+ "    \"properties\" : {\r\n"
    	+ "      \"JOpt.Algorithm.PreOptimization.SA.NumIterations\" : \"10000\",\r\n"
    	+ "      \"JOpt.NumCPUCores\" : \"4\",\r\n"
    	+ "      \"JOpt.Algorithm.PreOptimization.SA.NumRepetions\" : \"1\",\r\n"
    	+ "      \"JOptExitCondition.JOptGenerationCount\" : \"2000\"\r\n"
    	+ "    }\r\n"
    	+ "  },\r\n"
    	+ "  \"extension\" : {\r\n"
    	+ "    \"timeOut\" : \"PT10M\"\r\n"
    	+ "  }\r\n"
    	+ "}";
    
    
    
    public static final String DEFAULT_PNDBakeryChainFlexLoadExample ="{\r\n"
    	+ "  \"ident\" : \"JOpt-Run-1652344149097\",\r\n"
    	+ "  \"nodes\" : [ {\r\n"
    	+ "    \"id\" : \"StoreEssen\",\r\n"
    	+ "    \"type\" : {\r\n"
    	+ "      \"position\" : {\r\n"
    	+ "        \"latitude\" : 51.45,\r\n"
    	+ "        \"longitude\" : 7.01667,\r\n"
    	+ "        \"locationId\" : \"StoreEssen\"\r\n"
    	+ "      },\r\n"
    	+ "      \"typeName\" : \"Geo\"\r\n"
    	+ "    },\r\n"
    	+ "    \"openingHours\" : [ {\r\n"
    	+ "      \"begin\" : \"2020-03-11T07:00:00Z\",\r\n"
    	+ "      \"end\" : \"2020-03-11T17:00:00Z\",\r\n"
    	+ "      \"zoneId\" : \"Europe/Berlin\"\r\n"
    	+ "    } ],\r\n"
    	+ "    \"visitDuration\" : \"PT1H20M\",\r\n"
    	+ "    \"priority\" : 1,\r\n"
    	+ "    \"nodeDepot\" : {\r\n"
    	+ "      \"depotId\" : \"StoreEssenDepot\",\r\n"
    	+ "      \"items\" : [ {\r\n"
    	+ "        \"loadId\" : \"Bread\",\r\n"
    	+ "        \"loadValue\" : 5.0,\r\n"
    	+ "        \"priority\" : 1,\r\n"
    	+ "        \"isRequest\" : true,\r\n"
    	+ "        \"isFuzzyVisit\" : true,\r\n"
    	+ "        \"typeName\" : \"SimpleLoad\"\r\n"
    	+ "      } ],\r\n"
    	+ "      \"typeName\" : \"SimpleNodeDepot\"\r\n"
    	+ "    }\r\n"
    	+ "  }, {\r\n"
    	+ "    \"id\" : \"StoreDueren\",\r\n"
    	+ "    \"type\" : {\r\n"
    	+ "      \"position\" : {\r\n"
    	+ "        \"latitude\" : 50.8,\r\n"
    	+ "        \"longitude\" : 6.48333,\r\n"
    	+ "        \"locationId\" : \"StoreDueren\"\r\n"
    	+ "      },\r\n"
    	+ "      \"typeName\" : \"Geo\"\r\n"
    	+ "    },\r\n"
    	+ "    \"openingHours\" : [ {\r\n"
    	+ "      \"begin\" : \"2020-03-11T07:00:00Z\",\r\n"
    	+ "      \"end\" : \"2020-03-11T17:00:00Z\",\r\n"
    	+ "      \"zoneId\" : \"Europe/Berlin\"\r\n"
    	+ "    } ],\r\n"
    	+ "    \"visitDuration\" : \"PT1H20M\",\r\n"
    	+ "    \"priority\" : 1,\r\n"
    	+ "    \"nodeDepot\" : {\r\n"
    	+ "      \"depotId\" : \"StoreDuerenDepot\",\r\n"
    	+ "      \"items\" : [ {\r\n"
    	+ "        \"loadId\" : \"Bread\",\r\n"
    	+ "        \"loadValue\" : 2.0,\r\n"
    	+ "        \"priority\" : 1,\r\n"
    	+ "        \"isRequest\" : true,\r\n"
    	+ "        \"isFuzzyVisit\" : true,\r\n"
    	+ "        \"typeName\" : \"SimpleLoad\"\r\n"
    	+ "      } ],\r\n"
    	+ "      \"typeName\" : \"SimpleNodeDepot\"\r\n"
    	+ "    }\r\n"
    	+ "  }, {\r\n"
    	+ "    \"id\" : \"StoreWuppertal\",\r\n"
    	+ "    \"type\" : {\r\n"
    	+ "      \"position\" : {\r\n"
    	+ "        \"latitude\" : 51.2667,\r\n"
    	+ "        \"longitude\" : 7.18333,\r\n"
    	+ "        \"locationId\" : \"StoreWuppertal\"\r\n"
    	+ "      },\r\n"
    	+ "      \"typeName\" : \"Geo\"\r\n"
    	+ "    },\r\n"
    	+ "    \"openingHours\" : [ {\r\n"
    	+ "      \"begin\" : \"2020-03-11T07:00:00Z\",\r\n"
    	+ "      \"end\" : \"2020-03-11T17:00:00Z\",\r\n"
    	+ "      \"zoneId\" : \"Europe/Berlin\"\r\n"
    	+ "    } ],\r\n"
    	+ "    \"visitDuration\" : \"PT1H20M\",\r\n"
    	+ "    \"priority\" : 1,\r\n"
    	+ "    \"nodeDepot\" : {\r\n"
    	+ "      \"depotId\" : \"StoreWuppertalDepot\",\r\n"
    	+ "      \"items\" : [ {\r\n"
    	+ "        \"loadId\" : \"Bread\",\r\n"
    	+ "        \"loadValue\" : 4.0,\r\n"
    	+ "        \"priority\" : 1,\r\n"
    	+ "        \"isRequest\" : true,\r\n"
    	+ "        \"isFuzzyVisit\" : true,\r\n"
    	+ "        \"typeName\" : \"SimpleLoad\"\r\n"
    	+ "      } ],\r\n"
    	+ "      \"typeName\" : \"SimpleNodeDepot\"\r\n"
    	+ "    }\r\n"
    	+ "  }, {\r\n"
    	+ "    \"id\" : \"StoreDortmund\",\r\n"
    	+ "    \"type\" : {\r\n"
    	+ "      \"position\" : {\r\n"
    	+ "        \"latitude\" : 51.51728,\r\n"
    	+ "        \"longitude\" : 7.48446,\r\n"
    	+ "        \"locationId\" : \"StoreDortmund\"\r\n"
    	+ "      },\r\n"
    	+ "      \"typeName\" : \"Geo\"\r\n"
    	+ "    },\r\n"
    	+ "    \"openingHours\" : [ {\r\n"
    	+ "      \"begin\" : \"2020-03-11T07:00:00Z\",\r\n"
    	+ "      \"end\" : \"2020-03-11T17:00:00Z\",\r\n"
    	+ "      \"zoneId\" : \"Europe/Berlin\"\r\n"
    	+ "    } ],\r\n"
    	+ "    \"visitDuration\" : \"PT1H20M\",\r\n"
    	+ "    \"priority\" : 1,\r\n"
    	+ "    \"nodeDepot\" : {\r\n"
    	+ "      \"depotId\" : \"StoreDortmundDepot\",\r\n"
    	+ "      \"items\" : [ {\r\n"
    	+ "        \"loadId\" : \"Bread\",\r\n"
    	+ "        \"loadValue\" : 8.0,\r\n"
    	+ "        \"priority\" : 1,\r\n"
    	+ "        \"isRequest\" : true,\r\n"
    	+ "        \"isFuzzyVisit\" : true,\r\n"
    	+ "        \"typeName\" : \"SimpleLoad\"\r\n"
    	+ "      } ],\r\n"
    	+ "      \"typeName\" : \"SimpleNodeDepot\"\r\n"
    	+ "    }\r\n"
    	+ "  }, {\r\n"
    	+ "    \"id\" : \"StoreMoenchengladbach\",\r\n"
    	+ "    \"type\" : {\r\n"
    	+ "      \"position\" : {\r\n"
    	+ "        \"latitude\" : 51.19541,\r\n"
    	+ "        \"longitude\" : 6.41172,\r\n"
    	+ "        \"locationId\" : \"StoreMoenchengladbach\"\r\n"
    	+ "      },\r\n"
    	+ "      \"typeName\" : \"Geo\"\r\n"
    	+ "    },\r\n"
    	+ "    \"openingHours\" : [ {\r\n"
    	+ "      \"begin\" : \"2020-03-11T07:00:00Z\",\r\n"
    	+ "      \"end\" : \"2020-03-11T17:00:00Z\",\r\n"
    	+ "      \"zoneId\" : \"Europe/Berlin\"\r\n"
    	+ "    } ],\r\n"
    	+ "    \"visitDuration\" : \"PT1H20M\",\r\n"
    	+ "    \"priority\" : 1,\r\n"
    	+ "    \"nodeDepot\" : {\r\n"
    	+ "      \"depotId\" : \"StoreMoenchengladbachDepot\",\r\n"
    	+ "      \"items\" : [ {\r\n"
    	+ "        \"loadId\" : \"Bread\",\r\n"
    	+ "        \"loadValue\" : 1.0,\r\n"
    	+ "        \"priority\" : 1,\r\n"
    	+ "        \"isRequest\" : true,\r\n"
    	+ "        \"isFuzzyVisit\" : true,\r\n"
    	+ "        \"typeName\" : \"SimpleLoad\"\r\n"
    	+ "      } ],\r\n"
    	+ "      \"typeName\" : \"SimpleNodeDepot\"\r\n"
    	+ "    }\r\n"
    	+ "  }, {\r\n"
    	+ "    \"id\" : \"StoreLeverkusen\",\r\n"
    	+ "    \"type\" : {\r\n"
    	+ "      \"position\" : {\r\n"
    	+ "        \"latitude\" : 51.04154,\r\n"
    	+ "        \"longitude\" : 6.99944,\r\n"
    	+ "        \"locationId\" : \"StoreLeverkusen\"\r\n"
    	+ "      },\r\n"
    	+ "      \"typeName\" : \"Geo\"\r\n"
    	+ "    },\r\n"
    	+ "    \"openingHours\" : [ {\r\n"
    	+ "      \"begin\" : \"2020-03-11T07:00:00Z\",\r\n"
    	+ "      \"end\" : \"2020-03-11T17:00:00Z\",\r\n"
    	+ "      \"zoneId\" : \"Europe/Berlin\"\r\n"
    	+ "    } ],\r\n"
    	+ "    \"visitDuration\" : \"PT1H20M\",\r\n"
    	+ "    \"priority\" : 1,\r\n"
    	+ "    \"nodeDepot\" : {\r\n"
    	+ "      \"depotId\" : \"StoreLeverkusenDepot\",\r\n"
    	+ "      \"items\" : [ {\r\n"
    	+ "        \"loadId\" : \"Bread\",\r\n"
    	+ "        \"loadValue\" : 7.0,\r\n"
    	+ "        \"priority\" : 1,\r\n"
    	+ "        \"isRequest\" : true,\r\n"
    	+ "        \"isFuzzyVisit\" : true,\r\n"
    	+ "        \"typeName\" : \"SimpleLoad\"\r\n"
    	+ "      } ],\r\n"
    	+ "      \"typeName\" : \"SimpleNodeDepot\"\r\n"
    	+ "    }\r\n"
    	+ "  }, {\r\n"
    	+ "    \"id\" : \"SupplyFlexNodeAachen\",\r\n"
    	+ "    \"type\" : {\r\n"
    	+ "      \"position\" : {\r\n"
    	+ "        \"latitude\" : 50.77577,\r\n"
    	+ "        \"longitude\" : 6.08177,\r\n"
    	+ "        \"locationId\" : \"SupplyFlexNodeAachen\"\r\n"
    	+ "      },\r\n"
    	+ "      \"typeName\" : \"Geo\"\r\n"
    	+ "    },\r\n"
    	+ "    \"openingHours\" : [ {\r\n"
    	+ "      \"begin\" : \"2020-03-11T07:00:00Z\",\r\n"
    	+ "      \"end\" : \"2020-03-11T17:00:00Z\",\r\n"
    	+ "      \"zoneId\" : \"Europe/Berlin\"\r\n"
    	+ "    } ],\r\n"
    	+ "    \"visitDuration\" : \"PT1H20M\",\r\n"
    	+ "    \"priority\" : 1,\r\n"
    	+ "    \"nodeDepot\" : {\r\n"
    	+ "      \"depotId\" : \"SupplyFlexNodeAachenDepot\",\r\n"
    	+ "      \"items\" : [ {\r\n"
    	+ "        \"loadId\" : \"Bread\",\r\n"
    	+ "        \"loadValue\" : 20.0,\r\n"
    	+ "        \"isRequest\" : false,\r\n"
    	+ "        \"isFuzzyVisit\" : false,\r\n"
    	+ "        \"priority\" : 1,\r\n"
    	+ "        \"typeName\" : \"SupplyFlexLoad\"\r\n"
    	+ "      } ],\r\n"
    	+ "      \"typeName\" : \"SimpleNodeDepot\"\r\n"
    	+ "    }\r\n"
    	+ "  }, {\r\n"
    	+ "    \"id\" : \"SupplyFlexNodeCologne\",\r\n"
    	+ "    \"type\" : {\r\n"
    	+ "      \"position\" : {\r\n"
    	+ "        \"latitude\" : 50.9333,\r\n"
    	+ "        \"longitude\" : 6.95,\r\n"
    	+ "        \"locationId\" : \"SupplyFlexNodeCologne\"\r\n"
    	+ "      },\r\n"
    	+ "      \"typeName\" : \"Geo\"\r\n"
    	+ "    },\r\n"
    	+ "    \"openingHours\" : [ {\r\n"
    	+ "      \"begin\" : \"2020-03-11T07:00:00Z\",\r\n"
    	+ "      \"end\" : \"2020-03-11T17:00:00Z\",\r\n"
    	+ "      \"zoneId\" : \"Europe/Berlin\"\r\n"
    	+ "    } ],\r\n"
    	+ "    \"visitDuration\" : \"PT1H20M\",\r\n"
    	+ "    \"priority\" : 1,\r\n"
    	+ "    \"nodeDepot\" : {\r\n"
    	+ "      \"depotId\" : \"SupplyFlexNodeCologneDepot\",\r\n"
    	+ "      \"items\" : [ {\r\n"
    	+ "        \"loadId\" : \"Bread\",\r\n"
    	+ "        \"loadValue\" : 20.0,\r\n"
    	+ "        \"isRequest\" : false,\r\n"
    	+ "        \"isFuzzyVisit\" : false,\r\n"
    	+ "        \"priority\" : 1,\r\n"
    	+ "        \"typeName\" : \"SupplyFlexLoad\"\r\n"
    	+ "      } ],\r\n"
    	+ "      \"typeName\" : \"SimpleNodeDepot\"\r\n"
    	+ "    }\r\n"
    	+ "  } ],\r\n"
    	+ "  \"resources\" : [ {\r\n"
    	+ "    \"id\" : \"JackTruckCologne\",\r\n"
    	+ "    \"type\" : {\r\n"
    	+ "      \"typeName\" : \"Capacity\"\r\n"
    	+ "    },\r\n"
    	+ "    \"position\" : {\r\n"
    	+ "      \"latitude\" : 50.9333,\r\n"
    	+ "      \"longitude\" : 6.95,\r\n"
    	+ "      \"locationId\" : \"JackTruckCologne\"\r\n"
    	+ "    },\r\n"
    	+ "    \"workingHours\" : [ {\r\n"
    	+ "      \"begin\" : \"2020-03-11T07:00:00Z\",\r\n"
    	+ "      \"end\" : \"2020-03-11T19:00:00Z\",\r\n"
    	+ "      \"zoneId\" : \"Europe/Berlin\"\r\n"
    	+ "    } ],\r\n"
    	+ "    \"maxTime\" : \"PT10H\",\r\n"
    	+ "    \"maxDistance\" : \"2800.0 km\",\r\n"
    	+ "    \"co2emissionFactor\" : 0.377,\r\n"
    	+ "    \"resourceDepot\" : {\r\n"
    	+ "      \"depotId\" : \"JackTruckCologneDepot\",\r\n"
    	+ "      \"maximalUnitMatchedCapacity\" : 20.0,\r\n"
    	+ "      \"items\" : [ {\r\n"
    	+ "        \"loadCapacityId\" : \"Bread\",\r\n"
    	+ "        \"currentLoad\" : 0.0,\r\n"
    	+ "        \"maximalIndividualLoadCapacity\" : 20.0,\r\n"
    	+ "        \"typeName\" : \"SimpleLoadCapacity\"\r\n"
    	+ "      } ],\r\n"
    	+ "      \"typeName\" : \"SimpleResourceDepot\"\r\n"
    	+ "    }\r\n"
    	+ "  }, {\r\n"
    	+ "    \"id\" : \"JohnTruckAachen\",\r\n"
    	+ "    \"type\" : {\r\n"
    	+ "      \"typeName\" : \"Capacity\"\r\n"
    	+ "    },\r\n"
    	+ "    \"position\" : {\r\n"
    	+ "      \"latitude\" : 50.775346,\r\n"
    	+ "      \"longitude\" : 6.083887,\r\n"
    	+ "      \"locationId\" : \"JohnTruckAachen\"\r\n"
    	+ "    },\r\n"
    	+ "    \"workingHours\" : [ {\r\n"
    	+ "      \"begin\" : \"2020-03-11T07:00:00Z\",\r\n"
    	+ "      \"end\" : \"2020-03-11T19:00:00Z\",\r\n"
    	+ "      \"zoneId\" : \"Europe/Berlin\"\r\n"
    	+ "    } ],\r\n"
    	+ "    \"maxTime\" : \"PT10H\",\r\n"
    	+ "    \"maxDistance\" : \"2800.0 km\",\r\n"
    	+ "    \"co2emissionFactor\" : 0.377,\r\n"
    	+ "    \"resourceDepot\" : {\r\n"
    	+ "      \"depotId\" : \"JohnTruckAachenDepot\",\r\n"
    	+ "      \"maximalUnitMatchedCapacity\" : 20.0,\r\n"
    	+ "      \"items\" : [ {\r\n"
    	+ "        \"loadCapacityId\" : \"Bread\",\r\n"
    	+ "        \"currentLoad\" : 0.0,\r\n"
    	+ "        \"maximalIndividualLoadCapacity\" : 20.0,\r\n"
    	+ "        \"typeName\" : \"SimpleLoadCapacity\"\r\n"
    	+ "      } ],\r\n"
    	+ "      \"typeName\" : \"SimpleResourceDepot\"\r\n"
    	+ "    }\r\n"
    	+ "  } ],\r\n"
    	+ "  \"optimizationOptions\" : {\r\n"
    	+ "    \"properties\" : {\r\n"
    	+ "      \"JOpt.Algorithm.PreOptimization.SA.NumIterations\" : \"10000\",\r\n"
    	+ "      \"JOpt.NumCPUCores\" : \"4\",\r\n"
    	+ "      \"JOpt.Algorithm.PreOptimization.SA.NumRepetions\" : \"1\",\r\n"
    	+ "      \"JOptExitCondition.JOptGenerationCount\" : \"2000\"\r\n"
    	+ "    }\r\n"
    	+ "  },\r\n"
    	+ "  \"extension\" : {\r\n"
    	+ "    \"timeOut\" : \"PT10M\"\r\n"
    	+ "  }\r\n"
    	+ "}";
}
