package com.dna.jopt.rest.client.util.testinputcreation;

/*-
 * #%L
 * JOpt Java REST Client Examples
 * %%
 * Copyright (C) 2017 - 2022 DNA Evolutions GmbH
 * %%
 * This file is subject to the terms and conditions defined in file 'LICENSE.md',
 * which is part of this repository.
 * 
 * If not, see <https://www.dna-evolutions.com/agb-conditions-and-terms/>.
 * #L%
 */

public class TestSnapshotInput {
    
    
    private TestSnapshotInput() {
	// Nothing to do
    }

    public static String DEFAULT_PUBLIC_INPUT_JSON_WITHOUT_LICENSE = "{\r\n"
    	+ "  \"ident\" : \"MyJOptRun\",\r\n"
    	+ "  \"nodes\" : [ {\r\n"
    	+ "    \"id\" : \"Koeln\",\r\n"
    	+ "    \"type\" : {\r\n"
    	+ "      \"position\" : {\r\n"
    	+ "        \"latitude\" : 50.9333,\r\n"
    	+ "        \"longitude\" : 6.95,\r\n"
    	+ "        \"locationId\" : \"Koeln\"\r\n"
    	+ "      },\r\n"
    	+ "      \"typeName\" : \"Geo\"\r\n"
    	+ "    },\r\n"
    	+ "    \"openingHours\" : [ {\r\n"
    	+ "      \"begin\" : \"2025-05-06T06:00:00Z\",\r\n"
    	+ "      \"end\" : \"2025-05-06T15:00:00Z\",\r\n"
    	+ "      \"zoneId\" : \"Europe/Berlin\"\r\n"
    	+ "    }, {\r\n"
    	+ "      \"begin\" : \"2025-05-07T06:00:00Z\",\r\n"
    	+ "      \"end\" : \"2025-05-07T15:00:00Z\",\r\n"
    	+ "      \"zoneId\" : \"Europe/Berlin\"\r\n"
    	+ "    } ],\r\n"
    	+ "    \"visitDuration\" : \"PT20M\",\r\n"
    	+ "    \"priority\" : 1\r\n"
    	+ "  }, {\r\n"
    	+ "    \"id\" : \"Essen\",\r\n"
    	+ "    \"type\" : {\r\n"
    	+ "      \"position\" : {\r\n"
    	+ "        \"latitude\" : 51.45,\r\n"
    	+ "        \"longitude\" : 7.01667,\r\n"
    	+ "        \"locationId\" : \"Essen\"\r\n"
    	+ "      },\r\n"
    	+ "      \"typeName\" : \"Geo\"\r\n"
    	+ "    },\r\n"
    	+ "    \"openingHours\" : [ {\r\n"
    	+ "      \"begin\" : \"2025-05-06T06:00:00Z\",\r\n"
    	+ "      \"end\" : \"2025-05-06T15:00:00Z\",\r\n"
    	+ "      \"zoneId\" : \"Europe/Berlin\"\r\n"
    	+ "    }, {\r\n"
    	+ "      \"begin\" : \"2025-05-07T06:00:00Z\",\r\n"
    	+ "      \"end\" : \"2025-05-07T15:00:00Z\",\r\n"
    	+ "      \"zoneId\" : \"Europe/Berlin\"\r\n"
    	+ "    } ],\r\n"
    	+ "    \"visitDuration\" : \"PT20M\",\r\n"
    	+ "    \"priority\" : 1\r\n"
    	+ "  }, {\r\n"
    	+ "    \"id\" : \"Dueren\",\r\n"
    	+ "    \"type\" : {\r\n"
    	+ "      \"position\" : {\r\n"
    	+ "        \"latitude\" : 50.8,\r\n"
    	+ "        \"longitude\" : 6.48333,\r\n"
    	+ "        \"locationId\" : \"Dueren\"\r\n"
    	+ "      },\r\n"
    	+ "      \"typeName\" : \"Geo\"\r\n"
    	+ "    },\r\n"
    	+ "    \"openingHours\" : [ {\r\n"
    	+ "      \"begin\" : \"2025-05-06T06:00:00Z\",\r\n"
    	+ "      \"end\" : \"2025-05-06T15:00:00Z\",\r\n"
    	+ "      \"zoneId\" : \"Europe/Berlin\"\r\n"
    	+ "    }, {\r\n"
    	+ "      \"begin\" : \"2025-05-07T06:00:00Z\",\r\n"
    	+ "      \"end\" : \"2025-05-07T15:00:00Z\",\r\n"
    	+ "      \"zoneId\" : \"Europe/Berlin\"\r\n"
    	+ "    } ],\r\n"
    	+ "    \"visitDuration\" : \"PT20M\",\r\n"
    	+ "    \"priority\" : 1\r\n"
    	+ "  }, {\r\n"
    	+ "    \"id\" : \"Nuernberg\",\r\n"
    	+ "    \"type\" : {\r\n"
    	+ "      \"position\" : {\r\n"
    	+ "        \"latitude\" : 49.4478,\r\n"
    	+ "        \"longitude\" : 11.0683,\r\n"
    	+ "        \"locationId\" : \"Nuernberg\"\r\n"
    	+ "      },\r\n"
    	+ "      \"typeName\" : \"Geo\"\r\n"
    	+ "    },\r\n"
    	+ "    \"openingHours\" : [ {\r\n"
    	+ "      \"begin\" : \"2025-05-06T06:00:00Z\",\r\n"
    	+ "      \"end\" : \"2025-05-06T15:00:00Z\",\r\n"
    	+ "      \"zoneId\" : \"Europe/Berlin\"\r\n"
    	+ "    }, {\r\n"
    	+ "      \"begin\" : \"2025-05-07T06:00:00Z\",\r\n"
    	+ "      \"end\" : \"2025-05-07T15:00:00Z\",\r\n"
    	+ "      \"zoneId\" : \"Europe/Berlin\"\r\n"
    	+ "    } ],\r\n"
    	+ "    \"visitDuration\" : \"PT20M\",\r\n"
    	+ "    \"priority\" : 1\r\n"
    	+ "  }, {\r\n"
    	+ "    \"id\" : \"Heilbronn\",\r\n"
    	+ "    \"type\" : {\r\n"
    	+ "      \"position\" : {\r\n"
    	+ "        \"latitude\" : 49.1403,\r\n"
    	+ "        \"longitude\" : 9.22,\r\n"
    	+ "        \"locationId\" : \"Heilbronn\"\r\n"
    	+ "      },\r\n"
    	+ "      \"typeName\" : \"Geo\"\r\n"
    	+ "    },\r\n"
    	+ "    \"openingHours\" : [ {\r\n"
    	+ "      \"begin\" : \"2025-05-06T06:00:00Z\",\r\n"
    	+ "      \"end\" : \"2025-05-06T15:00:00Z\",\r\n"
    	+ "      \"zoneId\" : \"Europe/Berlin\"\r\n"
    	+ "    }, {\r\n"
    	+ "      \"begin\" : \"2025-05-07T06:00:00Z\",\r\n"
    	+ "      \"end\" : \"2025-05-07T15:00:00Z\",\r\n"
    	+ "      \"zoneId\" : \"Europe/Berlin\"\r\n"
    	+ "    } ],\r\n"
    	+ "    \"visitDuration\" : \"PT20M\",\r\n"
    	+ "    \"priority\" : 1\r\n"
    	+ "  }, {\r\n"
    	+ "    \"id\" : \"Wuppertal\",\r\n"
    	+ "    \"type\" : {\r\n"
    	+ "      \"position\" : {\r\n"
    	+ "        \"latitude\" : 51.2667,\r\n"
    	+ "        \"longitude\" : 7.18333,\r\n"
    	+ "        \"locationId\" : \"Wuppertal\"\r\n"
    	+ "      },\r\n"
    	+ "      \"typeName\" : \"Geo\"\r\n"
    	+ "    },\r\n"
    	+ "    \"openingHours\" : [ {\r\n"
    	+ "      \"begin\" : \"2025-05-06T06:00:00Z\",\r\n"
    	+ "      \"end\" : \"2025-05-06T15:00:00Z\",\r\n"
    	+ "      \"zoneId\" : \"Europe/Berlin\"\r\n"
    	+ "    }, {\r\n"
    	+ "      \"begin\" : \"2025-05-07T06:00:00Z\",\r\n"
    	+ "      \"end\" : \"2025-05-07T15:00:00Z\",\r\n"
    	+ "      \"zoneId\" : \"Europe/Berlin\"\r\n"
    	+ "    } ],\r\n"
    	+ "    \"visitDuration\" : \"PT20M\",\r\n"
    	+ "    \"priority\" : 1\r\n"
    	+ "  }, {\r\n"
    	+ "    \"id\" : \"Aachen\",\r\n"
    	+ "    \"type\" : {\r\n"
    	+ "      \"position\" : {\r\n"
    	+ "        \"latitude\" : 50.775346,\r\n"
    	+ "        \"longitude\" : 6.083887,\r\n"
    	+ "        \"locationId\" : \"Aachen\"\r\n"
    	+ "      },\r\n"
    	+ "      \"typeName\" : \"Geo\"\r\n"
    	+ "    },\r\n"
    	+ "    \"openingHours\" : [ {\r\n"
    	+ "      \"begin\" : \"2025-05-06T06:00:00Z\",\r\n"
    	+ "      \"end\" : \"2025-05-06T15:00:00Z\",\r\n"
    	+ "      \"zoneId\" : \"Europe/Berlin\"\r\n"
    	+ "    }, {\r\n"
    	+ "      \"begin\" : \"2025-05-07T06:00:00Z\",\r\n"
    	+ "      \"end\" : \"2025-05-07T15:00:00Z\",\r\n"
    	+ "      \"zoneId\" : \"Europe/Berlin\"\r\n"
    	+ "    } ],\r\n"
    	+ "    \"visitDuration\" : \"PT20M\",\r\n"
    	+ "    \"priority\" : 1\r\n"
    	+ "  } ],\r\n"
    	+ "  \"resources\" : [ {\r\n"
    	+ "    \"id\" : \"Jack from Aachen\",\r\n"
    	+ "    \"type\" : {\r\n"
    	+ "      \"typeName\" : \"Capacity\"\r\n"
    	+ "    },\r\n"
    	+ "    \"position\" : {\r\n"
    	+ "      \"latitude\" : 50.775346,\r\n"
    	+ "      \"longitude\" : 6.083887,\r\n"
    	+ "      \"locationId\" : \"Jack from Aachen\"\r\n"
    	+ "    },\r\n"
    	+ "    \"workingHours\" : [ {\r\n"
    	+ "      \"begin\" : \"2025-05-06T06:00:00Z\",\r\n"
    	+ "      \"end\" : \"2025-05-06T15:00:00Z\",\r\n"
    	+ "      \"zoneId\" : \"Europe/Berlin\"\r\n"
    	+ "    }, {\r\n"
    	+ "      \"begin\" : \"2025-05-07T06:00:00Z\",\r\n"
    	+ "      \"end\" : \"2025-05-07T15:00:00Z\",\r\n"
    	+ "      \"zoneId\" : \"Europe/Berlin\"\r\n"
    	+ "    } ],\r\n"
    	+ "    \"maxTime\" : \"PT9H\",\r\n"
    	+ "    \"maxDistance\" : \"1200.0 km\",\r\n"
    	+ "    \"co2emissionFactor\" : 0.377\r\n"
    	+ "  } ],\r\n"
    	+ "  \"optimizationOptions\" : {\r\n"
    	+ "    \"properties\" : {\r\n"
    	+ "      \"JOpt.Algorithm.PreOptimization.SA.NumIterations\" : \"10000\",\r\n"
    	+ "      \"JOpt.NumCPUCores\" : \"4\",\r\n"
    	+ "      \"JOpt.Algorithm.PreOptimization.SA.NumRepetions\" : \"1\",\r\n"
    	+ "      \"JOptExitCondition.JOptGenerationCount\" : \"2000\"\r\n"
    	+ "    }\r\n"
    	+ "  },\r\n"
    	+ "  \"extension\" : {\r\n"
    	+ "    \"timeOut\" : \"PT10M\"\r\n"
    	+ "  }\r\n"
    	+ "}";
}
