package com.dna.jopt.rest.client.util.testinputcreation;

public class TestConnectionInput {
    
    
    private TestConnectionInput() {
	// Nothing to do
    }

    public static final String SYDNEY_CONNECTION_JSON_TEST_INPUT = "[ {\r\n" + "  \"fromElementId\" : \"Node_0\",\r\n"
	    + "  \"toElementId\" : \"Node_0\",\r\n" + "  \"type\" : {\r\n" + "    \"distance\" : \"0.0 km\",\r\n"
	    + "    \"time\" : \"PT0S\",\r\n" + "    \"fromPosition\" : {\r\n" + "      \"latitude\" : -34.052052,\r\n"
	    + "      \"longitude\" : 150.668724,\r\n" + "      \"locationId\" : \"Node_0\",\r\n"
	    + "      \"geoAddress\" : null,\r\n" + "      \"locationParameters\" : null\r\n" + "    },\r\n"
	    + "    \"toPosition\" : {\r\n" + "      \"latitude\" : -34.052052,\r\n"
	    + "      \"longitude\" : 150.668724,\r\n" + "      \"locationId\" : \"Node_0\",\r\n"
	    + "      \"geoAddress\" : null,\r\n" + "      \"locationParameters\" : null\r\n" + "    },\r\n"
	    + "    \"connectionByTime\" : null,\r\n" + "    \"typeName\" : \"Edge\"\r\n" + "  }\r\n" + "}, {\r\n"
	    + "  \"fromElementId\" : \"Node_0\",\r\n" + "  \"toElementId\" : \"Node_1\",\r\n" + "  \"type\" : {\r\n"
	    + "    \"distance\" : \"4.878 km\",\r\n" + "    \"time\" : \"PT5M32S\",\r\n"
	    + "    \"fromPosition\" : {\r\n" + "      \"latitude\" : -34.052052,\r\n"
	    + "      \"longitude\" : 150.668724,\r\n" + "      \"locationId\" : \"Node_0\",\r\n"
	    + "      \"geoAddress\" : null,\r\n" + "      \"locationParameters\" : null\r\n" + "    },\r\n"
	    + "    \"toPosition\" : {\r\n" + "      \"latitude\" : -34.052518,\r\n"
	    + "      \"longitude\" : 150.709943,\r\n" + "      \"locationId\" : \"Node_1\",\r\n"
	    + "      \"geoAddress\" : null,\r\n" + "      \"locationParameters\" : null\r\n" + "    },\r\n"
	    + "    \"connectionByTime\" : null,\r\n" + "    \"typeName\" : \"Edge\"\r\n" + "  }\r\n" + "}, {\r\n"
	    + "  \"fromElementId\" : \"Node_0\",\r\n" + "  \"toElementId\" : \"Node_2\",\r\n" + "  \"type\" : {\r\n"
	    + "    \"distance\" : \"7.172 km\",\r\n" + "    \"time\" : \"PT8M15S\",\r\n"
	    + "    \"fromPosition\" : {\r\n" + "      \"latitude\" : -34.052052,\r\n"
	    + "      \"longitude\" : 150.668724,\r\n" + "      \"locationId\" : \"Node_0\",\r\n"
	    + "      \"geoAddress\" : null,\r\n" + "      \"locationParameters\" : null\r\n" + "    },\r\n"
	    + "    \"toPosition\" : {\r\n" + "      \"latitude\" : -34.051988,\r\n"
	    + "      \"longitude\" : 150.71981,\r\n" + "      \"locationId\" : \"Node_2\",\r\n"
	    + "      \"geoAddress\" : null,\r\n" + "      \"locationParameters\" : null\r\n" + "    },\r\n"
	    + "    \"connectionByTime\" : null,\r\n" + "    \"typeName\" : \"Edge\"\r\n" + "  }\r\n" + "}, {\r\n"
	    + "  \"fromElementId\" : \"Node_0\",\r\n" + "  \"toElementId\" : \"Node_3\",\r\n" + "  \"type\" : {\r\n"
	    + "    \"distance\" : \"7.017 km\",\r\n" + "    \"time\" : \"PT7M32S\",\r\n"
	    + "    \"fromPosition\" : {\r\n" + "      \"latitude\" : -34.052052,\r\n"
	    + "      \"longitude\" : 150.668724,\r\n" + "      \"locationId\" : \"Node_0\",\r\n"
	    + "      \"geoAddress\" : null,\r\n" + "      \"locationParameters\" : null\r\n" + "    },\r\n"
	    + "    \"toPosition\" : {\r\n" + "      \"latitude\" : -34.04213,\r\n"
	    + "      \"longitude\" : 150.729568,\r\n" + "      \"locationId\" : \"Node_3\",\r\n"
	    + "      \"geoAddress\" : null,\r\n" + "      \"locationParameters\" : null\r\n" + "    },\r\n"
	    + "    \"connectionByTime\" : null,\r\n" + "    \"typeName\" : \"Edge\"\r\n" + "  }\r\n" + "}, {\r\n"
	    + "  \"fromElementId\" : \"Node_0\",\r\n" + "  \"toElementId\" : \"Node_4\",\r\n" + "  \"type\" : {\r\n"
	    + "    \"distance\" : \"8.265 km\",\r\n" + "    \"time\" : \"PT9M13S\",\r\n"
	    + "    \"fromPosition\" : {\r\n" + "      \"latitude\" : -34.052052,\r\n"
	    + "      \"longitude\" : 150.668724,\r\n" + "      \"locationId\" : \"Node_0\",\r\n"
	    + "      \"geoAddress\" : null,\r\n" + "      \"locationParameters\" : null\r\n" + "    },\r\n"
	    + "    \"toPosition\" : {\r\n" + "      \"latitude\" : -34.042063,\r\n"
	    + "      \"longitude\" : 150.739632,\r\n" + "      \"locationId\" : \"Node_4\",\r\n"
	    + "      \"geoAddress\" : null,\r\n" + "      \"locationParameters\" : null\r\n" + "    },\r\n"
	    + "    \"connectionByTime\" : null,\r\n" + "    \"typeName\" : \"Edge\"\r\n" + "  }\r\n" + "}, {\r\n"
	    + "  \"fromElementId\" : \"Node_0\",\r\n" + "  \"toElementId\" : \"Resource_0\",\r\n" + "  \"type\" : {\r\n"
	    + "    \"distance\" : \"0.0 km\",\r\n" + "    \"time\" : \"PT0S\",\r\n" + "    \"fromPosition\" : {\r\n"
	    + "      \"latitude\" : -34.052052,\r\n" + "      \"longitude\" : 150.668724,\r\n"
	    + "      \"locationId\" : \"Node_0\",\r\n" + "      \"geoAddress\" : null,\r\n"
	    + "      \"locationParameters\" : null\r\n" + "    },\r\n" + "    \"toPosition\" : {\r\n"
	    + "      \"latitude\" : -34.052052,\r\n" + "      \"longitude\" : 150.668724,\r\n"
	    + "      \"locationId\" : \"Resource_0\",\r\n" + "      \"geoAddress\" : null,\r\n"
	    + "      \"locationParameters\" : null\r\n" + "    },\r\n" + "    \"connectionByTime\" : null,\r\n"
	    + "    \"typeName\" : \"Edge\"\r\n" + "  }\r\n" + "}, {\r\n" + "  \"fromElementId\" : \"Node_1\",\r\n"
	    + "  \"toElementId\" : \"Node_0\",\r\n" + "  \"type\" : {\r\n" + "    \"distance\" : \"4.898 km\",\r\n"
	    + "    \"time\" : \"PT5M35S\",\r\n" + "    \"fromPosition\" : {\r\n"
	    + "      \"latitude\" : -34.052518,\r\n" + "      \"longitude\" : 150.709943,\r\n"
	    + "      \"locationId\" : \"Node_1\",\r\n" + "      \"geoAddress\" : null,\r\n"
	    + "      \"locationParameters\" : null\r\n" + "    },\r\n" + "    \"toPosition\" : {\r\n"
	    + "      \"latitude\" : -34.052052,\r\n" + "      \"longitude\" : 150.668724,\r\n"
	    + "      \"locationId\" : \"Node_0\",\r\n" + "      \"geoAddress\" : null,\r\n"
	    + "      \"locationParameters\" : null\r\n" + "    },\r\n" + "    \"connectionByTime\" : null,\r\n"
	    + "    \"typeName\" : \"Edge\"\r\n" + "  }\r\n" + "}, {\r\n" + "  \"fromElementId\" : \"Node_1\",\r\n"
	    + "  \"toElementId\" : \"Node_1\",\r\n" + "  \"type\" : {\r\n" + "    \"distance\" : \"0.0 km\",\r\n"
	    + "    \"time\" : \"PT0S\",\r\n" + "    \"fromPosition\" : {\r\n" + "      \"latitude\" : -34.052518,\r\n"
	    + "      \"longitude\" : 150.709943,\r\n" + "      \"locationId\" : \"Node_1\",\r\n"
	    + "      \"geoAddress\" : null,\r\n" + "      \"locationParameters\" : null\r\n" + "    },\r\n"
	    + "    \"toPosition\" : {\r\n" + "      \"latitude\" : -34.052518,\r\n"
	    + "      \"longitude\" : 150.709943,\r\n" + "      \"locationId\" : \"Node_1\",\r\n"
	    + "      \"geoAddress\" : null,\r\n" + "      \"locationParameters\" : null\r\n" + "    },\r\n"
	    + "    \"connectionByTime\" : null,\r\n" + "    \"typeName\" : \"Edge\"\r\n" + "  }\r\n" + "}, {\r\n"
	    + "  \"fromElementId\" : \"Node_1\",\r\n" + "  \"toElementId\" : \"Node_2\",\r\n" + "  \"type\" : {\r\n"
	    + "    \"distance\" : \"2.354 km\",\r\n" + "    \"time\" : \"PT3M7S\",\r\n" + "    \"fromPosition\" : {\r\n"
	    + "      \"latitude\" : -34.052518,\r\n" + "      \"longitude\" : 150.709943,\r\n"
	    + "      \"locationId\" : \"Node_1\",\r\n" + "      \"geoAddress\" : null,\r\n"
	    + "      \"locationParameters\" : null\r\n" + "    },\r\n" + "    \"toPosition\" : {\r\n"
	    + "      \"latitude\" : -34.051988,\r\n" + "      \"longitude\" : 150.71981,\r\n"
	    + "      \"locationId\" : \"Node_2\",\r\n" + "      \"geoAddress\" : null,\r\n"
	    + "      \"locationParameters\" : null\r\n" + "    },\r\n" + "    \"connectionByTime\" : null,\r\n"
	    + "    \"typeName\" : \"Edge\"\r\n" + "  }\r\n" + "}, {\r\n" + "  \"fromElementId\" : \"Node_1\",\r\n"
	    + "  \"toElementId\" : \"Node_3\",\r\n" + "  \"type\" : {\r\n" + "    \"distance\" : \"2.199 km\",\r\n"
	    + "    \"time\" : \"PT2M23S\",\r\n" + "    \"fromPosition\" : {\r\n"
	    + "      \"latitude\" : -34.052518,\r\n" + "      \"longitude\" : 150.709943,\r\n"
	    + "      \"locationId\" : \"Node_1\",\r\n" + "      \"geoAddress\" : null,\r\n"
	    + "      \"locationParameters\" : null\r\n" + "    },\r\n" + "    \"toPosition\" : {\r\n"
	    + "      \"latitude\" : -34.04213,\r\n" + "      \"longitude\" : 150.729568,\r\n"
	    + "      \"locationId\" : \"Node_3\",\r\n" + "      \"geoAddress\" : null,\r\n"
	    + "      \"locationParameters\" : null\r\n" + "    },\r\n" + "    \"connectionByTime\" : null,\r\n"
	    + "    \"typeName\" : \"Edge\"\r\n" + "  }\r\n" + "}, {\r\n" + "  \"fromElementId\" : \"Node_1\",\r\n"
	    + "  \"toElementId\" : \"Node_4\",\r\n" + "  \"type\" : {\r\n" + "    \"distance\" : \"3.447 km\",\r\n"
	    + "    \"time\" : \"PT4M4S\",\r\n" + "    \"fromPosition\" : {\r\n" + "      \"latitude\" : -34.052518,\r\n"
	    + "      \"longitude\" : 150.709943,\r\n" + "      \"locationId\" : \"Node_1\",\r\n"
	    + "      \"geoAddress\" : null,\r\n" + "      \"locationParameters\" : null\r\n" + "    },\r\n"
	    + "    \"toPosition\" : {\r\n" + "      \"latitude\" : -34.042063,\r\n"
	    + "      \"longitude\" : 150.739632,\r\n" + "      \"locationId\" : \"Node_4\",\r\n"
	    + "      \"geoAddress\" : null,\r\n" + "      \"locationParameters\" : null\r\n" + "    },\r\n"
	    + "    \"connectionByTime\" : null,\r\n" + "    \"typeName\" : \"Edge\"\r\n" + "  }\r\n" + "}, {\r\n"
	    + "  \"fromElementId\" : \"Node_1\",\r\n" + "  \"toElementId\" : \"Resource_0\",\r\n" + "  \"type\" : {\r\n"
	    + "    \"distance\" : \"4.898 km\",\r\n" + "    \"time\" : \"PT5M35S\",\r\n"
	    + "    \"fromPosition\" : {\r\n" + "      \"latitude\" : -34.052518,\r\n"
	    + "      \"longitude\" : 150.709943,\r\n" + "      \"locationId\" : \"Node_1\",\r\n"
	    + "      \"geoAddress\" : null,\r\n" + "      \"locationParameters\" : null\r\n" + "    },\r\n"
	    + "    \"toPosition\" : {\r\n" + "      \"latitude\" : -34.052052,\r\n"
	    + "      \"longitude\" : 150.668724,\r\n" + "      \"locationId\" : \"Resource_0\",\r\n"
	    + "      \"geoAddress\" : null,\r\n" + "      \"locationParameters\" : null\r\n" + "    },\r\n"
	    + "    \"connectionByTime\" : null,\r\n" + "    \"typeName\" : \"Edge\"\r\n" + "  }\r\n" + "}, {\r\n"
	    + "  \"fromElementId\" : \"Node_2\",\r\n" + "  \"toElementId\" : \"Node_0\",\r\n" + "  \"type\" : {\r\n"
	    + "    \"distance\" : \"7.171 km\",\r\n" + "    \"time\" : \"PT8M19S\",\r\n"
	    + "    \"fromPosition\" : {\r\n" + "      \"latitude\" : -34.051988,\r\n"
	    + "      \"longitude\" : 150.71981,\r\n" + "      \"locationId\" : \"Node_2\",\r\n"
	    + "      \"geoAddress\" : null,\r\n" + "      \"locationParameters\" : null\r\n" + "    },\r\n"
	    + "    \"toPosition\" : {\r\n" + "      \"latitude\" : -34.052052,\r\n"
	    + "      \"longitude\" : 150.668724,\r\n" + "      \"locationId\" : \"Node_0\",\r\n"
	    + "      \"geoAddress\" : null,\r\n" + "      \"locationParameters\" : null\r\n" + "    },\r\n"
	    + "    \"connectionByTime\" : null,\r\n" + "    \"typeName\" : \"Edge\"\r\n" + "  }\r\n" + "}, {\r\n"
	    + "  \"fromElementId\" : \"Node_2\",\r\n" + "  \"toElementId\" : \"Node_1\",\r\n" + "  \"type\" : {\r\n"
	    + "    \"distance\" : \"2.333 km\",\r\n" + "    \"time\" : \"PT3M4S\",\r\n" + "    \"fromPosition\" : {\r\n"
	    + "      \"latitude\" : -34.051988,\r\n" + "      \"longitude\" : 150.71981,\r\n"
	    + "      \"locationId\" : \"Node_2\",\r\n" + "      \"geoAddress\" : null,\r\n"
	    + "      \"locationParameters\" : null\r\n" + "    },\r\n" + "    \"toPosition\" : {\r\n"
	    + "      \"latitude\" : -34.052518,\r\n" + "      \"longitude\" : 150.709943,\r\n"
	    + "      \"locationId\" : \"Node_1\",\r\n" + "      \"geoAddress\" : null,\r\n"
	    + "      \"locationParameters\" : null\r\n" + "    },\r\n" + "    \"connectionByTime\" : null,\r\n"
	    + "    \"typeName\" : \"Edge\"\r\n" + "  }\r\n" + "}, {\r\n" + "  \"fromElementId\" : \"Node_2\",\r\n"
	    + "  \"toElementId\" : \"Node_2\",\r\n" + "  \"type\" : {\r\n" + "    \"distance\" : \"0.0 km\",\r\n"
	    + "    \"time\" : \"PT0S\",\r\n" + "    \"fromPosition\" : {\r\n" + "      \"latitude\" : -34.051988,\r\n"
	    + "      \"longitude\" : 150.71981,\r\n" + "      \"locationId\" : \"Node_2\",\r\n"
	    + "      \"geoAddress\" : null,\r\n" + "      \"locationParameters\" : null\r\n" + "    },\r\n"
	    + "    \"toPosition\" : {\r\n" + "      \"latitude\" : -34.051988,\r\n"
	    + "      \"longitude\" : 150.71981,\r\n" + "      \"locationId\" : \"Node_2\",\r\n"
	    + "      \"geoAddress\" : null,\r\n" + "      \"locationParameters\" : null\r\n" + "    },\r\n"
	    + "    \"connectionByTime\" : null,\r\n" + "    \"typeName\" : \"Edge\"\r\n" + "  }\r\n" + "}, {\r\n"
	    + "  \"fromElementId\" : \"Node_2\",\r\n" + "  \"toElementId\" : \"Node_3\",\r\n" + "  \"type\" : {\r\n"
	    + "    \"distance\" : \"3.471 km\",\r\n" + "    \"time\" : \"PT4M14S\",\r\n"
	    + "    \"fromPosition\" : {\r\n" + "      \"latitude\" : -34.051988,\r\n"
	    + "      \"longitude\" : 150.71981,\r\n" + "      \"locationId\" : \"Node_2\",\r\n"
	    + "      \"geoAddress\" : null,\r\n" + "      \"locationParameters\" : null\r\n" + "    },\r\n"
	    + "    \"toPosition\" : {\r\n" + "      \"latitude\" : -34.04213,\r\n"
	    + "      \"longitude\" : 150.729568,\r\n" + "      \"locationId\" : \"Node_3\",\r\n"
	    + "      \"geoAddress\" : null,\r\n" + "      \"locationParameters\" : null\r\n" + "    },\r\n"
	    + "    \"connectionByTime\" : null,\r\n" + "    \"typeName\" : \"Edge\"\r\n" + "  }\r\n" + "}, {\r\n"
	    + "  \"fromElementId\" : \"Node_2\",\r\n" + "  \"toElementId\" : \"Node_4\",\r\n" + "  \"type\" : {\r\n"
	    + "    \"distance\" : \"3.286 km\",\r\n" + "    \"time\" : \"PT4M34S\",\r\n"
	    + "    \"fromPosition\" : {\r\n" + "      \"latitude\" : -34.051988,\r\n"
	    + "      \"longitude\" : 150.71981,\r\n" + "      \"locationId\" : \"Node_2\",\r\n"
	    + "      \"geoAddress\" : null,\r\n" + "      \"locationParameters\" : null\r\n" + "    },\r\n"
	    + "    \"toPosition\" : {\r\n" + "      \"latitude\" : -34.042063,\r\n"
	    + "      \"longitude\" : 150.739632,\r\n" + "      \"locationId\" : \"Node_4\",\r\n"
	    + "      \"geoAddress\" : null,\r\n" + "      \"locationParameters\" : null\r\n" + "    },\r\n"
	    + "    \"connectionByTime\" : null,\r\n" + "    \"typeName\" : \"Edge\"\r\n" + "  }\r\n" + "}, {\r\n"
	    + "  \"fromElementId\" : \"Node_2\",\r\n" + "  \"toElementId\" : \"Resource_0\",\r\n" + "  \"type\" : {\r\n"
	    + "    \"distance\" : \"7.171 km\",\r\n" + "    \"time\" : \"PT8M19S\",\r\n"
	    + "    \"fromPosition\" : {\r\n" + "      \"latitude\" : -34.051988,\r\n"
	    + "      \"longitude\" : 150.71981,\r\n" + "      \"locationId\" : \"Node_2\",\r\n"
	    + "      \"geoAddress\" : null,\r\n" + "      \"locationParameters\" : null\r\n" + "    },\r\n"
	    + "    \"toPosition\" : {\r\n" + "      \"latitude\" : -34.052052,\r\n"
	    + "      \"longitude\" : 150.668724,\r\n" + "      \"locationId\" : \"Resource_0\",\r\n"
	    + "      \"geoAddress\" : null,\r\n" + "      \"locationParameters\" : null\r\n" + "    },\r\n"
	    + "    \"connectionByTime\" : null,\r\n" + "    \"typeName\" : \"Edge\"\r\n" + "  }\r\n" + "}, {\r\n"
	    + "  \"fromElementId\" : \"Node_3\",\r\n" + "  \"toElementId\" : \"Node_0\",\r\n" + "  \"type\" : {\r\n"
	    + "    \"distance\" : \"7.024 km\",\r\n" + "    \"time\" : \"PT7M34S\",\r\n"
	    + "    \"fromPosition\" : {\r\n" + "      \"latitude\" : -34.04213,\r\n"
	    + "      \"longitude\" : 150.729568,\r\n" + "      \"locationId\" : \"Node_3\",\r\n"
	    + "      \"geoAddress\" : null,\r\n" + "      \"locationParameters\" : null\r\n" + "    },\r\n"
	    + "    \"toPosition\" : {\r\n" + "      \"latitude\" : -34.052052,\r\n"
	    + "      \"longitude\" : 150.668724,\r\n" + "      \"locationId\" : \"Node_0\",\r\n"
	    + "      \"geoAddress\" : null,\r\n" + "      \"locationParameters\" : null\r\n" + "    },\r\n"
	    + "    \"connectionByTime\" : null,\r\n" + "    \"typeName\" : \"Edge\"\r\n" + "  }\r\n" + "}, {\r\n"
	    + "  \"fromElementId\" : \"Node_3\",\r\n" + "  \"toElementId\" : \"Node_1\",\r\n" + "  \"type\" : {\r\n"
	    + "    \"distance\" : \"2.186 km\",\r\n" + "    \"time\" : \"PT2M20S\",\r\n"
	    + "    \"fromPosition\" : {\r\n" + "      \"latitude\" : -34.04213,\r\n"
	    + "      \"longitude\" : 150.729568,\r\n" + "      \"locationId\" : \"Node_3\",\r\n"
	    + "      \"geoAddress\" : null,\r\n" + "      \"locationParameters\" : null\r\n" + "    },\r\n"
	    + "    \"toPosition\" : {\r\n" + "      \"latitude\" : -34.052518,\r\n"
	    + "      \"longitude\" : 150.709943,\r\n" + "      \"locationId\" : \"Node_1\",\r\n"
	    + "      \"geoAddress\" : null,\r\n" + "      \"locationParameters\" : null\r\n" + "    },\r\n"
	    + "    \"connectionByTime\" : null,\r\n" + "    \"typeName\" : \"Edge\"\r\n" + "  }\r\n" + "}, {\r\n"
	    + "  \"fromElementId\" : \"Node_3\",\r\n" + "  \"toElementId\" : \"Node_2\",\r\n" + "  \"type\" : {\r\n"
	    + "    \"distance\" : \"3.46 km\",\r\n" + "    \"time\" : \"PT4M3S\",\r\n" + "    \"fromPosition\" : {\r\n"
	    + "      \"latitude\" : -34.04213,\r\n" + "      \"longitude\" : 150.729568,\r\n"
	    + "      \"locationId\" : \"Node_3\",\r\n" + "      \"geoAddress\" : null,\r\n"
	    + "      \"locationParameters\" : null\r\n" + "    },\r\n" + "    \"toPosition\" : {\r\n"
	    + "      \"latitude\" : -34.051988,\r\n" + "      \"longitude\" : 150.71981,\r\n"
	    + "      \"locationId\" : \"Node_2\",\r\n" + "      \"geoAddress\" : null,\r\n"
	    + "      \"locationParameters\" : null\r\n" + "    },\r\n" + "    \"connectionByTime\" : null,\r\n"
	    + "    \"typeName\" : \"Edge\"\r\n" + "  }\r\n" + "}, {\r\n" + "  \"fromElementId\" : \"Node_3\",\r\n"
	    + "  \"toElementId\" : \"Node_3\",\r\n" + "  \"type\" : {\r\n" + "    \"distance\" : \"0.0 km\",\r\n"
	    + "    \"time\" : \"PT0S\",\r\n" + "    \"fromPosition\" : {\r\n" + "      \"latitude\" : -34.04213,\r\n"
	    + "      \"longitude\" : 150.729568,\r\n" + "      \"locationId\" : \"Node_3\",\r\n"
	    + "      \"geoAddress\" : null,\r\n" + "      \"locationParameters\" : null\r\n" + "    },\r\n"
	    + "    \"toPosition\" : {\r\n" + "      \"latitude\" : -34.04213,\r\n"
	    + "      \"longitude\" : 150.729568,\r\n" + "      \"locationId\" : \"Node_3\",\r\n"
	    + "      \"geoAddress\" : null,\r\n" + "      \"locationParameters\" : null\r\n" + "    },\r\n"
	    + "    \"connectionByTime\" : null,\r\n" + "    \"typeName\" : \"Edge\"\r\n" + "  }\r\n" + "}, {\r\n"
	    + "  \"fromElementId\" : \"Node_3\",\r\n" + "  \"toElementId\" : \"Node_4\",\r\n" + "  \"type\" : {\r\n"
	    + "    \"distance\" : \"1.248 km\",\r\n" + "    \"time\" : \"PT1M41S\",\r\n"
	    + "    \"fromPosition\" : {\r\n" + "      \"latitude\" : -34.04213,\r\n"
	    + "      \"longitude\" : 150.729568,\r\n" + "      \"locationId\" : \"Node_3\",\r\n"
	    + "      \"geoAddress\" : null,\r\n" + "      \"locationParameters\" : null\r\n" + "    },\r\n"
	    + "    \"toPosition\" : {\r\n" + "      \"latitude\" : -34.042063,\r\n"
	    + "      \"longitude\" : 150.739632,\r\n" + "      \"locationId\" : \"Node_4\",\r\n"
	    + "      \"geoAddress\" : null,\r\n" + "      \"locationParameters\" : null\r\n" + "    },\r\n"
	    + "    \"connectionByTime\" : null,\r\n" + "    \"typeName\" : \"Edge\"\r\n" + "  }\r\n" + "}, {\r\n"
	    + "  \"fromElementId\" : \"Node_3\",\r\n" + "  \"toElementId\" : \"Resource_0\",\r\n" + "  \"type\" : {\r\n"
	    + "    \"distance\" : \"7.024 km\",\r\n" + "    \"time\" : \"PT7M34S\",\r\n"
	    + "    \"fromPosition\" : {\r\n" + "      \"latitude\" : -34.04213,\r\n"
	    + "      \"longitude\" : 150.729568,\r\n" + "      \"locationId\" : \"Node_3\",\r\n"
	    + "      \"geoAddress\" : null,\r\n" + "      \"locationParameters\" : null\r\n" + "    },\r\n"
	    + "    \"toPosition\" : {\r\n" + "      \"latitude\" : -34.052052,\r\n"
	    + "      \"longitude\" : 150.668724,\r\n" + "      \"locationId\" : \"Resource_0\",\r\n"
	    + "      \"geoAddress\" : null,\r\n" + "      \"locationParameters\" : null\r\n" + "    },\r\n"
	    + "    \"connectionByTime\" : null,\r\n" + "    \"typeName\" : \"Edge\"\r\n" + "  }\r\n" + "}, {\r\n"
	    + "  \"fromElementId\" : \"Node_4\",\r\n" + "  \"toElementId\" : \"Node_0\",\r\n" + "  \"type\" : {\r\n"
	    + "    \"distance\" : \"8.293 km\",\r\n" + "    \"time\" : \"PT9M13S\",\r\n"
	    + "    \"fromPosition\" : {\r\n" + "      \"latitude\" : -34.042063,\r\n"
	    + "      \"longitude\" : 150.739632,\r\n" + "      \"locationId\" : \"Node_4\",\r\n"
	    + "      \"geoAddress\" : null,\r\n" + "      \"locationParameters\" : null\r\n" + "    },\r\n"
	    + "    \"toPosition\" : {\r\n" + "      \"latitude\" : -34.052052,\r\n"
	    + "      \"longitude\" : 150.668724,\r\n" + "      \"locationId\" : \"Node_0\",\r\n"
	    + "      \"geoAddress\" : null,\r\n" + "      \"locationParameters\" : null\r\n" + "    },\r\n"
	    + "    \"connectionByTime\" : null,\r\n" + "    \"typeName\" : \"Edge\"\r\n" + "  }\r\n" + "}, {\r\n"
	    + "  \"fromElementId\" : \"Node_4\",\r\n" + "  \"toElementId\" : \"Node_1\",\r\n" + "  \"type\" : {\r\n"
	    + "    \"distance\" : \"3.455 km\",\r\n" + "    \"time\" : \"PT3M58S\",\r\n"
	    + "    \"fromPosition\" : {\r\n" + "      \"latitude\" : -34.042063,\r\n"
	    + "      \"longitude\" : 150.739632,\r\n" + "      \"locationId\" : \"Node_4\",\r\n"
	    + "      \"geoAddress\" : null,\r\n" + "      \"locationParameters\" : null\r\n" + "    },\r\n"
	    + "    \"toPosition\" : {\r\n" + "      \"latitude\" : -34.052518,\r\n"
	    + "      \"longitude\" : 150.709943,\r\n" + "      \"locationId\" : \"Node_1\",\r\n"
	    + "      \"geoAddress\" : null,\r\n" + "      \"locationParameters\" : null\r\n" + "    },\r\n"
	    + "    \"connectionByTime\" : null,\r\n" + "    \"typeName\" : \"Edge\"\r\n" + "  }\r\n" + "}, {\r\n"
	    + "  \"fromElementId\" : \"Node_4\",\r\n" + "  \"toElementId\" : \"Node_2\",\r\n" + "  \"type\" : {\r\n"
	    + "    \"distance\" : \"3.298 km\",\r\n" + "    \"time\" : \"PT4M41S\",\r\n"
	    + "    \"fromPosition\" : {\r\n" + "      \"latitude\" : -34.042063,\r\n"
	    + "      \"longitude\" : 150.739632,\r\n" + "      \"locationId\" : \"Node_4\",\r\n"
	    + "      \"geoAddress\" : null,\r\n" + "      \"locationParameters\" : null\r\n" + "    },\r\n"
	    + "    \"toPosition\" : {\r\n" + "      \"latitude\" : -34.051988,\r\n"
	    + "      \"longitude\" : 150.71981,\r\n" + "      \"locationId\" : \"Node_2\",\r\n"
	    + "      \"geoAddress\" : null,\r\n" + "      \"locationParameters\" : null\r\n" + "    },\r\n"
	    + "    \"connectionByTime\" : null,\r\n" + "    \"typeName\" : \"Edge\"\r\n" + "  }\r\n" + "}, {\r\n"
	    + "  \"fromElementId\" : \"Node_4\",\r\n" + "  \"toElementId\" : \"Node_3\",\r\n" + "  \"type\" : {\r\n"
	    + "    \"distance\" : \"1.269 km\",\r\n" + "    \"time\" : \"PT1M38S\",\r\n"
	    + "    \"fromPosition\" : {\r\n" + "      \"latitude\" : -34.042063,\r\n"
	    + "      \"longitude\" : 150.739632,\r\n" + "      \"locationId\" : \"Node_4\",\r\n"
	    + "      \"geoAddress\" : null,\r\n" + "      \"locationParameters\" : null\r\n" + "    },\r\n"
	    + "    \"toPosition\" : {\r\n" + "      \"latitude\" : -34.04213,\r\n"
	    + "      \"longitude\" : 150.729568,\r\n" + "      \"locationId\" : \"Node_3\",\r\n"
	    + "      \"geoAddress\" : null,\r\n" + "      \"locationParameters\" : null\r\n" + "    },\r\n"
	    + "    \"connectionByTime\" : null,\r\n" + "    \"typeName\" : \"Edge\"\r\n" + "  }\r\n" + "}, {\r\n"
	    + "  \"fromElementId\" : \"Node_4\",\r\n" + "  \"toElementId\" : \"Node_4\",\r\n" + "  \"type\" : {\r\n"
	    + "    \"distance\" : \"0.0 km\",\r\n" + "    \"time\" : \"PT0S\",\r\n" + "    \"fromPosition\" : {\r\n"
	    + "      \"latitude\" : -34.042063,\r\n" + "      \"longitude\" : 150.739632,\r\n"
	    + "      \"locationId\" : \"Node_4\",\r\n" + "      \"geoAddress\" : null,\r\n"
	    + "      \"locationParameters\" : null\r\n" + "    },\r\n" + "    \"toPosition\" : {\r\n"
	    + "      \"latitude\" : -34.042063,\r\n" + "      \"longitude\" : 150.739632,\r\n"
	    + "      \"locationId\" : \"Node_4\",\r\n" + "      \"geoAddress\" : null,\r\n"
	    + "      \"locationParameters\" : null\r\n" + "    },\r\n" + "    \"connectionByTime\" : null,\r\n"
	    + "    \"typeName\" : \"Edge\"\r\n" + "  }\r\n" + "}, {\r\n" + "  \"fromElementId\" : \"Node_4\",\r\n"
	    + "  \"toElementId\" : \"Resource_0\",\r\n" + "  \"type\" : {\r\n" + "    \"distance\" : \"8.293 km\",\r\n"
	    + "    \"time\" : \"PT9M13S\",\r\n" + "    \"fromPosition\" : {\r\n"
	    + "      \"latitude\" : -34.042063,\r\n" + "      \"longitude\" : 150.739632,\r\n"
	    + "      \"locationId\" : \"Node_4\",\r\n" + "      \"geoAddress\" : null,\r\n"
	    + "      \"locationParameters\" : null\r\n" + "    },\r\n" + "    \"toPosition\" : {\r\n"
	    + "      \"latitude\" : -34.052052,\r\n" + "      \"longitude\" : 150.668724,\r\n"
	    + "      \"locationId\" : \"Resource_0\",\r\n" + "      \"geoAddress\" : null,\r\n"
	    + "      \"locationParameters\" : null\r\n" + "    },\r\n" + "    \"connectionByTime\" : null,\r\n"
	    + "    \"typeName\" : \"Edge\"\r\n" + "  }\r\n" + "}, {\r\n" + "  \"fromElementId\" : \"Resource_0\",\r\n"
	    + "  \"toElementId\" : \"Node_0\",\r\n" + "  \"type\" : {\r\n" + "    \"distance\" : \"0.0 km\",\r\n"
	    + "    \"time\" : \"PT0S\",\r\n" + "    \"fromPosition\" : {\r\n" + "      \"latitude\" : -34.052052,\r\n"
	    + "      \"longitude\" : 150.668724,\r\n" + "      \"locationId\" : \"Resource_0\",\r\n"
	    + "      \"geoAddress\" : null,\r\n" + "      \"locationParameters\" : null\r\n" + "    },\r\n"
	    + "    \"toPosition\" : {\r\n" + "      \"latitude\" : -34.052052,\r\n"
	    + "      \"longitude\" : 150.668724,\r\n" + "      \"locationId\" : \"Node_0\",\r\n"
	    + "      \"geoAddress\" : null,\r\n" + "      \"locationParameters\" : null\r\n" + "    },\r\n"
	    + "    \"connectionByTime\" : null,\r\n" + "    \"typeName\" : \"Edge\"\r\n" + "  }\r\n" + "}, {\r\n"
	    + "  \"fromElementId\" : \"Resource_0\",\r\n" + "  \"toElementId\" : \"Node_1\",\r\n" + "  \"type\" : {\r\n"
	    + "    \"distance\" : \"4.878 km\",\r\n" + "    \"time\" : \"PT5M32S\",\r\n"
	    + "    \"fromPosition\" : {\r\n" + "      \"latitude\" : -34.052052,\r\n"
	    + "      \"longitude\" : 150.668724,\r\n" + "      \"locationId\" : \"Resource_0\",\r\n"
	    + "      \"geoAddress\" : null,\r\n" + "      \"locationParameters\" : null\r\n" + "    },\r\n"
	    + "    \"toPosition\" : {\r\n" + "      \"latitude\" : -34.052518,\r\n"
	    + "      \"longitude\" : 150.709943,\r\n" + "      \"locationId\" : \"Node_1\",\r\n"
	    + "      \"geoAddress\" : null,\r\n" + "      \"locationParameters\" : null\r\n" + "    },\r\n"
	    + "    \"connectionByTime\" : null,\r\n" + "    \"typeName\" : \"Edge\"\r\n" + "  }\r\n" + "}, {\r\n"
	    + "  \"fromElementId\" : \"Resource_0\",\r\n" + "  \"toElementId\" : \"Node_2\",\r\n" + "  \"type\" : {\r\n"
	    + "    \"distance\" : \"7.172 km\",\r\n" + "    \"time\" : \"PT8M15S\",\r\n"
	    + "    \"fromPosition\" : {\r\n" + "      \"latitude\" : -34.052052,\r\n"
	    + "      \"longitude\" : 150.668724,\r\n" + "      \"locationId\" : \"Resource_0\",\r\n"
	    + "      \"geoAddress\" : null,\r\n" + "      \"locationParameters\" : null\r\n" + "    },\r\n"
	    + "    \"toPosition\" : {\r\n" + "      \"latitude\" : -34.051988,\r\n"
	    + "      \"longitude\" : 150.71981,\r\n" + "      \"locationId\" : \"Node_2\",\r\n"
	    + "      \"geoAddress\" : null,\r\n" + "      \"locationParameters\" : null\r\n" + "    },\r\n"
	    + "    \"connectionByTime\" : null,\r\n" + "    \"typeName\" : \"Edge\"\r\n" + "  }\r\n" + "}, {\r\n"
	    + "  \"fromElementId\" : \"Resource_0\",\r\n" + "  \"toElementId\" : \"Node_3\",\r\n" + "  \"type\" : {\r\n"
	    + "    \"distance\" : \"7.017 km\",\r\n" + "    \"time\" : \"PT7M32S\",\r\n"
	    + "    \"fromPosition\" : {\r\n" + "      \"latitude\" : -34.052052,\r\n"
	    + "      \"longitude\" : 150.668724,\r\n" + "      \"locationId\" : \"Resource_0\",\r\n"
	    + "      \"geoAddress\" : null,\r\n" + "      \"locationParameters\" : null\r\n" + "    },\r\n"
	    + "    \"toPosition\" : {\r\n" + "      \"latitude\" : -34.04213,\r\n"
	    + "      \"longitude\" : 150.729568,\r\n" + "      \"locationId\" : \"Node_3\",\r\n"
	    + "      \"geoAddress\" : null,\r\n" + "      \"locationParameters\" : null\r\n" + "    },\r\n"
	    + "    \"connectionByTime\" : null,\r\n" + "    \"typeName\" : \"Edge\"\r\n" + "  }\r\n" + "}, {\r\n"
	    + "  \"fromElementId\" : \"Resource_0\",\r\n" + "  \"toElementId\" : \"Node_4\",\r\n" + "  \"type\" : {\r\n"
	    + "    \"distance\" : \"8.265 km\",\r\n" + "    \"time\" : \"PT9M13S\",\r\n"
	    + "    \"fromPosition\" : {\r\n" + "      \"latitude\" : -34.052052,\r\n"
	    + "      \"longitude\" : 150.668724,\r\n" + "      \"locationId\" : \"Resource_0\",\r\n"
	    + "      \"geoAddress\" : null,\r\n" + "      \"locationParameters\" : null\r\n" + "    },\r\n"
	    + "    \"toPosition\" : {\r\n" + "      \"latitude\" : -34.042063,\r\n"
	    + "      \"longitude\" : 150.739632,\r\n" + "      \"locationId\" : \"Node_4\",\r\n"
	    + "      \"geoAddress\" : null,\r\n" + "      \"locationParameters\" : null\r\n" + "    },\r\n"
	    + "    \"connectionByTime\" : null,\r\n" + "    \"typeName\" : \"Edge\"\r\n" + "  }\r\n" + "}, {\r\n"
	    + "  \"fromElementId\" : \"Resource_0\",\r\n" + "  \"toElementId\" : \"Resource_0\",\r\n"
	    + "  \"type\" : {\r\n" + "    \"distance\" : \"0.0 km\",\r\n" + "    \"time\" : \"PT0S\",\r\n"
	    + "    \"fromPosition\" : {\r\n" + "      \"latitude\" : -34.052052,\r\n"
	    + "      \"longitude\" : 150.668724,\r\n" + "      \"locationId\" : \"Resource_0\",\r\n"
	    + "      \"geoAddress\" : null,\r\n" + "      \"locationParameters\" : null\r\n" + "    },\r\n"
	    + "    \"toPosition\" : {\r\n" + "      \"latitude\" : -34.052052,\r\n"
	    + "      \"longitude\" : 150.668724,\r\n" + "      \"locationId\" : \"Resource_0\",\r\n"
	    + "      \"geoAddress\" : null,\r\n" + "      \"locationParameters\" : null\r\n" + "    },\r\n"
	    + "    \"connectionByTime\" : null,\r\n" + "    \"typeName\" : \"Edge\"\r\n" + "  }\r\n" + "} ]";

}
